### ISSUE TITLE
 reconnect() too many time

### ISSUE THREAD

**Issue by redmiix24** [mdn522/expertoptionapi#1]
ERROR:root:**error** reconnect() too many time please look log file

**Comment by mdn522** [comment]
I am not focusing on this API as I don't have a very good relation with ExpertOption. They instantly blocked several accounts upon detecting automated traded profit.

*They don't allow robots as mentioned in their T&C

**Comment by redmiix24** [comment]
@mdn522 Thank you dear Abdullah for your great information
do you know any binary option website that accepts API or WS (websocket) ?
except IQ Option
Thank you

**Comment by mdn522** [comment]
You can take a look at https://github.com/mdn522/binaryapi
It's based on Binary.com's Websocket
Most of the low-level API was added. it's not perfect yet but it can do the job
This issue might help if you choose to give it a try
https://github.com/mdn522/binaryapi/issues/3

Apart from that. I tried Pocket Option. they seem to not like it when we make a profit. got instantly blocked for new accounts. an old account on hold for verification still

It's tricky to withdraw significant profit from binary options brokers

**Comment by redmiix24** [comment]
Thank you dear for all the information you provided. I will take a look at it

**Comment by rajkiranjeet** [comment]
Hi
any example of API how to do login and send order

**Comment by mdn522** [comment]
> Hi any example of API how to do login and send order

#2
