### ISSUE TITLE
Hi any example of API how to add headers websocket ,user-agent,origin and host.

### ISSUE THREAD

**Issue by rahmangunawans** [mdn522/expertoptionapi#3]
how  add headers websocket?

**Comment by mdn522** [comment]
I can refer to these to links


In this file you will find WebSocket client/app initialization
https://github.com/mdn522/expertoptionapi/blob/master/expertoptionapi/ws/client.py#L17

Documentation for WebSocket app
https://websocket-client.readthedocs.io/en/latest/app.html#websocket._app.WebSocketApp


But you should know that I have long abandoned this project.

**Comment by theshadow76** [comment]
You can check the newer version here!
https://github.com/theshadow76/ExpertOptionApi
