### ISSUE TITLE
I want to continue this project

### ISSUE THREAD

**Issue by theshadow76** [mdn522/expertoptionapi#5]
Hello! 
My name is Vigo Walker. I wanted to know if you would allow me to keep working on this project, I want to add the possibility to buy and sell, also add other things like the possibility to get real time data from the markets and a way to access indicators.

So let me know!

**Comment by mdn522** [comment]
Thank you for your interest in this project. 
The reason I abandoned this project is back in 2020-21 I tried to trade using bots. but Expert Option immediately blocked my account. then I found that it's against their ToS to use bots

now, about your proposal. you can continue this project. I can make you an collaborator if you like.

**Comment by theshadow76** [comment]
Yes, please, I would like to be a collaborator in the project.

By the way, do you know why using bots is against their ToS? 

Do you think I should contact them?

**Comment by mdn522** [comment]
I have sent you the request(about collaborator). you should see a notification/email.

About using bots, It's their rule. We can't say anything about it. If they detect bot like trading or any patterns that is humanly impossible, they might ban. you have to find it the hard way if they are still banning. I did back in 2020 and got banned. I don't know about the current situation. You have to find out if they do.

You can anonymousely contact them. there's no harm in asking.
